version: "2.0"

services:
    candybot:
        image: candybot:public
        container_name: candybot-public
        restart: on-failure
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - /var/bots/CandyBot:/app/data:rw
        working_dir: /app
        entrypoint: /app/binaries/bin/CandyBot
